sonar.projectKey=digital-Garden
sonar.projectName=Digital Garden
sonar.sourceEncoding=UTF-8

sonar.sources=client/src,server/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
